// Daten von Testuser zurückgeben - read
GET /users HTTP/1.1
Host: localhost:8080

###
// neuen User anlegen - create
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{"username":"Testusername","vorname":"Testvorname","nachname":"Testnachname","passwort":"Testpasswort"}

###
// Daten von Testuser zurückgeben - read
GET /user/Testusername2 HTTP/1.1
Host: localhost:8080

###
// Daten von Testuser aktualisieren - update
PUT /user/Testusername HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{"username":"Testusername","vorname":"Testvorname1","nachname":"Testnachname2"}

###
// Testuser löschen - delete
DELETE /user/Testusername HTTP/2
Host: localhost:8080

###
GET / HTTP/2
Host: localhost:8080

###
// neues Tier anlegen - create
POST /pet HTTP/2
Host: localhost:8080
Content-Type: application/json

{"tiername":"Testtiername","tierart":"Testtierart"}

###
// Daten von Testtier zurückgeben - read
GET /pet/Testtiername HTTP/1.1
Host: localhost:8080

###
// Daten von Testtier aktualisieren - update
PUT /pet/Testtiername HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{"tiername":"Testtiername","tiertart":"Testtierart"}

###
// Testtier löschen - delete
DELETE /pet/Testtiername HTTP/2
Host: localhost:8080
